os: linux
dist: bionic
language: shell

env:
  jobs:
    - TOX_ENV=ubuntu1804-ansible28
    - TOX_ENV=ubuntu1804-ansible29
    - TOX_ENV=ubuntu2004-ansible28
    - TOX_ENV=ubuntu2004-ansible29

before_install:
  - |
    curl -Os https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
    curl -Os https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_SHA256SUMS
    sha256sum -c vagrant_2.2.9_SHA256SUMS 2>&1 | grep OK
    sudo apt-get update
    sudo apt-get install ovmf qemu-kvm libvirt-daemon-system libvirt-clients \
                 bridge-utils virt-manager qemu-utils qemu-block-extra \
                 ruby-libvirt qemu libvirt-dev zlib1g-dev ruby-dev \
                 python3
    sudo dpkg -i vagrant_2.2.9_x86_64.deb
    vagrant plugin install vagrant-libvirt
    pip3 install tox

script: 
  - |
    echo ${TOX_ENV}
    vagrant --version
    python --version
