name: ansible ci

on:
  - push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Install LXD and CI tools
        run: |
          sudo apt update
          sudo apt install lxd lxd-tools qemu-block-extra python3 python3-pip python3-setuptools

      - name: Configure LXD
        run: |
          sudo lxd init --auto
          sudo usermod -aG lxd $(whoami)

      - name: Install tox using python3-pip
        run: |
          sudo pip3 install tox

      - name: Check lxc info
        run: sudo lxc info

      - name: Check lxc list
        run: sudo lxc list

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: ansible-ci
        run: |
          sudo tox -e ubuntu2004-ansible29 -c ansible-ci-module/tox.ini
